### ISSUE TITLE
Add support for alternate http ports

### ISSUE THREAD

**Issue by jedibrand** [adamwg/tracks-android#8] opened 2011-01-20 22:04 UTC
I would of course prefer https, but failing that, alternate http ports would be nice for those of us that can't serve tracks via port 80!

**Comment by adamwg** [comment] 2011-01-20 22:18
Absolutely near the top of my todo list.  This will probably come either with HTTPS or before HTTPS.

**Comment by adamwg** [comment] 2011-01-22 22:14
Alternate ports working, closed by 73f48ec7ecff799f500e67afee15e709054043c9.  HTTPS probably works with a good cert, but this is untested.

**Closed as completed** 2011-01-23 06:14 UTC
Labels: enhancement

**Comment by jedibrand** [comment] 2011-01-25 03:06
Thanks Adam, that was fast! I updated the app via the Market. I see the following options:
1. Server Port
2. Use HTTPS?
3. Ignore Certificate Errors

WIthout HTTPS, I enter my alternate HTTP port in Server Port. The rest of the settings match those that I have in the app "Shuffle", which works fine. However, when I exit settings in Tracks for Android all I get is "fetch error".

I've also tested using HTTPS by enabling that option and using "https://..." for the server address. Same result--"fetch error"

**Comment by adamwg** [comment] 2011-01-25 03:40
Are you putting the https:// in the Server Address box?  If so, that's what is causing the problem - that box needs only the server address itself.  I've tried https and alternate ports with my Tracks server, and I'm not seeing any problems.

If you try taking that out, and the problem is still there, is it possible for you to send me a logcat output?  Or, if it's possible for me to get an account on your Tracks server I can test it that way.

**Comment by jedibrand** [comment] 2011-01-25 04:21
Thanks Adam. I was pre-pending http:// and https:// in the server address. I've removed that and tried both alternate port and https. It then reads "Fetching data", and eventually "Fetch error."

I'm emailing you a test account to my server.

**Comment by adamwg** [comment] 2011-01-26 05:14
Thanks for the test account.

The problem was with servers (like yours) where Tracks doesn't live at the root.  That is, Tracks is at example.com/my/tracks/install instead of just tracks.example.com.

The problem is fixed in the latest version (1.3).  You should get an update notification from the Market.

**Comment by jedibrand** [comment] 2011-01-27 15:50
I suspected that. I should have given you all the details--I apologize for that.

I can report that now it works with HTTPS, and all is well with the world again ;-).

**Comment by adamwg** [comment] 2011-01-27 16:27
Great!  Glad it's working.
